language: r
cache: packages

before_script:
  - chmod +x ./_deploy.sh

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
  - ./_deploy.sh
